# -*- coding: utf-8 -*-
"""RestAPI_MatrizDistancia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hxsj5tGLrz3HWiOgEse_InwzkHAeeCaT
"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /drive/ngrok-ssh
# %cd /drive/ngrok-ssh
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok-stable-linux-amd64.zip
!unzip -u ngrok-stable-linux-amd64.zip
!cp /drive/ngrok-ssh/ngrok /ngrok
!chmod +x /ngrok

!pip install flask flask-ngroka

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as r
import math
app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def home():
  return "<marquee><h3> BIENVENIDO A MI REST API. Atte. Esteban Palomino Valdivia.</h3></marquee>"

@app.route('/matrix', methods=['POST'])
def predJson():
  data = request.get_json()
  cx_origen = data['LatitudCliente']
  cy_origen = data['LongitudCliente']
  cx_destino = data['LatitudBodega']
  cy_destino = data['LongitudBodega']
  dist = math.sqrt(math.pow((cx_origen-cx_destino),2) + math.pow((cy_origen-cy_destino),2))
  dist = round(dist, 3)
  nd = {
    "calculo": "distancia"
      }
  nd["distancia"] = dist
  return jsonify(nd)
app.run()